// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8P4GSE9tW5sA6wAT0eGQOUdj7fPehbJ4',
    appId: '1:497968049454:web:3b396d68d54f8b3f06debf',
    messagingSenderId: '497968049454',
    projectId: 'ewoda-1b55d',
    authDomain: 'ewoda-1b55d.firebaseapp.com',
    storageBucket: 'ewoda-1b55d.appspot.com',
    measurementId: 'G-NZPQGTF2TC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4pkcGlc7g4iRizIidhta4YS9TWPtEtE4',
    appId: '1:497968049454:android:473d878e2912119506debf',
    messagingSenderId: '497968049454',
    projectId: 'ewoda-1b55d',
    storageBucket: 'ewoda-1b55d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeHcDJuxH12bx4dma6XwdxVbjDnUIqwa8',
    appId: '1:497968049454:ios:67cf7ed27ad40ca806debf',
    messagingSenderId: '497968049454',
    projectId: 'ewoda-1b55d',
    storageBucket: 'ewoda-1b55d.appspot.com',
    iosClientId: '497968049454-9a17eo40dsk5knn2osuv27llnhc10s72.apps.googleusercontent.com',
    iosBundleId: 'com.example.eWoda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeHcDJuxH12bx4dma6XwdxVbjDnUIqwa8',
    appId: '1:497968049454:ios:67cf7ed27ad40ca806debf',
    messagingSenderId: '497968049454',
    projectId: 'ewoda-1b55d',
    storageBucket: 'ewoda-1b55d.appspot.com',
    iosClientId: '497968049454-9a17eo40dsk5knn2osuv27llnhc10s72.apps.googleusercontent.com',
    iosBundleId: 'com.example.eWoda',
  );
}
